name = "ShelfSpaceAllocation"
uuid = "97feaf0c-89bb-11e9-0f61-254e188ba389"
authors = ["Jaan Tollander de Balsch <jaan.tollander@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
JuMP = ">= 0.19"
julia = "1.0"
